[platformio]
src_dir = main
boards_dir = boards

[env:hakimi_serial_audio_v3]
platform = espressif32
board = esp32-p4-wlk2802-32mb
framework = espidf
custom_p4_chip_family = v3
board_build.f_cpu = 400000000L
board_build.flash_size = 32MB
board_upload.flash_size = 32MB
# This CH343 path showed packet corruption at 921600 during esptool's baud
# switch. 460800 is the stable flashing speed; the runtime link is still 4M.
upload_speed = 460800
monitor_speed = 115200
extra_scripts =
  scripts/bound_p4_image.py
